# Generated by Django 3.2.7 on 2021-11-03 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=10)),
                ('brand', models.CharField(choices=[('7-Eleven', '7-Eleven'), ('Ampol', 'Ampol'), ('BP', 'BP'), ('Budget', 'Budget'), ('Caltex', 'Caltex'), ('Caltex Woolworths', 'Caltex Woolworths'), ('Coles Express', 'Coles Express'), ('Costco', 'Costco'), ('Enhance', 'Enhance'), ('Independent', 'Independent'), ('Inland Petroleum', 'Inland Petroleum'), ('Liberty', 'Liberty'), ('Lowes', 'Lowes'), ('Matilda', 'Matilda'), ('Metro Fuel', 'Metro Fuel'), ('Mobil', 'Mobil'), ('Mobil 1', 'Mobil 1'), ('NRMA', 'NRMA'), ('Prime Petroleum', 'Prime Petroleum'), ('Puma Energy', 'Puma Energy'), ('Shell', 'Shell'), ('South West', 'South West'), ('Speedway', 'Speedway'), ('Tesla', 'Tesla'), ('Transwest Fuels', 'Transwest Fuels'), ('United', 'United'), ('Westside', 'Westside'), ('Woodham Petroleum', 'Woodham Petroleum')], max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('postcode', models.SmallIntegerField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('state', models.CharField(choices=[('NSW', 'New South Wales'), ('TAS', 'Tasmania')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Update time')),
                ('fuel', models.CharField(choices=[('E10', 'Ethanol 94'), ('U91', 'Unleaded 91'), ('E85', 'Ethanol 105'), ('P95', 'Premium 95'), ('P98', 'Premium 98'), ('DL', 'Diesel'), ('PDL', 'Premium Diesel'), ('B20', 'Biodiesel 20'), ('LPG', 'LPG'), ('CNG', 'CNG/NGV'), ('EV', 'EV charge')], max_length=3, verbose_name='Fuel Type')),
                ('price', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend.station')),
            ],
        ),
    ]
