# Generated by Django 3.2.7 on 2021-11-04 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='station_name',
            new_name='name',
        ),
    ]
