# Generated by Django 3.2.7 on 2021-11-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0002_rename_station_name_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
